server:
    port: 5000

spring:
    datasource:
        url: jdbc:mysql://duck-shop-db.crzucsfqxps5.ap-northeast-1.rds.amazonaws.com:3306/duck-shop?useSSL=false&allowPublicKeyRetrieval=true
        username: admin
        password: atPfkh8!
    data:
        redis:
            use-redis-cache: true
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            password: ${REDIS_PASSWORD:}
            #spring.data.redis.use-redis-cache
            #host: ${REDIS_HOST:ubuntu-server-01.local} # Default to 'localhost' if not provided

