logging:
    level:
        org:
            springframework:
                security: debug
    file:
        name: log/dev.log
    group:
        tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
    pattern:
        level: INFO

spring:
    application:
        name: duck-shop
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                jdbc:
                    time_zone: Asia/Ho_Chi_Minh
        show-sql: true
    profiles:
        active: dev

    http:
        encoding:
            charset: UTF-8
    mvc:
        charset: UTF-8
    messages:
        basename: message
        encoding: UTF-8
        use-code-as-default-message: true
    web:
        locale: vi
        locale-resolver: fixed

app:
    jwt-secret: 38a0963a6364b09ad867aa9a66c6d009673c21e182015461da236ec361877f77
    jwt-expiration-milliseconds: 604800000 #1week
    cloudinary:
        cloud_name: dkurral2z
        api_key: 778991549327989
        api_secret: L9_wohW70nyFwZtEQu3GscjcouM
        folder_name: duck_shop

paging:
    default:
        page-number: 1
        page-size: 24

vnpay:
    tmn-code: ZCZAPALE
    hash-secret: EJWBFDLNDPPPGNODNZRFXZDEJPTAELNT
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    return-url: /api/v1/vnpay/vnpay-payment

ghn:
    shop-id: 192001
    token: 91b6b238-00c8-11ef-a6e6-e60958111f48


